tor-chromium: Rewrite script
* Disable WebGL to decrease leaked information about the PC thereby
  hardening against fingerprinting (add some references)
* Disable local DNS queries
* Check for various requirements at the beginning instead of spanning if
  statements over the whole code block
* Remove the temporary directory after quitting the browser
* Tune the filter for extracting the IP address
* Disable flash for sure

diff --git a/bin/tor-chromium b/bin/tor-chromium
--- a/bin/tor-chromium
+++ b/bin/tor-chromium
@@ -1,18 +1,43 @@
 #!/bin/bash
 
-# Chromium using tor proxy
-if which chromium &>/dev/null; then
-	if which systemctl &>/dev/null; then
-		[[ $(systemctl is-active tor) != "active" ]] && systemctl start tor
-	else
-		echo "Could not verify that Tor is running, please make sure it is. Proceeding anyway!"
-	fi
-	[[ -d /tmp/cache-tor-chromium ]] || mkdir -p /tmp/private-chromium-cache
-	torify curl -s ipinfo.io 2>&1 | grep -i "\"ip\"" | sed "s/ip/fake-ip/" | tr -d ",\n"
-	echo -n "  |"
-	curl -s ipinfo.io 2>&1 | grep -i "\"ip\"" | sed "s/ip/true-ip/" | tr -d ","
-	echo -e "\e[1mStarting chromium in incognito modus, keeping the cache in /tmp and using the local tor-proxy.\e[0m"
-	chromium --incognito --disk-cache-dir=/tmp/private-chromium-cache --proxy-server="socks://localhost:9050"
-else
+# A privacy enabled version of chromium using tor proxy and various command line flags
+# in order to disguise the user's location and to hide identifiable information.
+
+
+if ! which chromium &>/dev/null; then
 	echo "Could not find chromium!"
+	exit 1
 fi
+if which systemctl &>/dev/null; then
+	[[ $(systemctl is-active tor) != "active" ]] && systemctl start tor
+else
+	echo "Could not verify that Tor is running, please make sure it is. Proceeding anyway!"
+fi
+
+# Create a temporary dir
+tmpdir=$(mktemp -q -p /tmp -t -d "private_chromium".XXX)
+
+# Print some information about the new IP address and chromium configuration
+curl -s --preprox socks5://localhost:9050 ipinfo.io 2>&1 | sed -n 's/^.*ip\":[^0-9]*\([0-9\.]*\).*$/fake-ip: \1/p'
+curl -s ipinfo.io 2>&1 | sed -n 's/^.*ip\":[^0-9]*\([0-9\.]*\).*$/real-ip: \1/p'
+echo -e "\e[1mStarting chromium in incognito modus, disabling custom DNS services, keeping the cache in /tmp and using the local tor-proxy.\e[0m"
+
+chromium_args=(
+	--incognito
+	--disk-cache-dir=\"${tmpdir}\"
+	--proxy-server="socks5://localhost:9050"
+	# Disable local DNS queries which might circumvent the socks proxy
+	--host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE localhost"
+	# Limit the amount of trackable information (disables interactive 3D graphics)
+	--disable-webgl
+	# Disable flash for sure
+	--disable-plugins-discovery
+	--disable-internal-flash)
+chromium "${chromium_args[@]}" https://check.torproject.org/
+
+# Check for trackability at
+# https://panopticlick.eff.org/results?#fingerprintTable
+# http://uniquemachine.org/
+
+# Remove temporary dir
+rm -rf "${tmpdir}"
